Artww/Artww/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('index/', include('index.urls')),
    path('artwork/', include('artwork.urls')),
    path('countries/', include('countries.urls')),
    path('artists/', include('artists.urls')),
    path('accounts/', include('login.urls')),
    path('search/', include('search.urls')),
    path('lists/', include('lists.urls')),
]

Artww/login/models.py
from django.db import models
from datetime import timedelta
from django.utils.timezone import now
from parameterized import parameterized
from index.models import language
from django.contrib.auth.models import User
from django.conf import settings
from artwork.models import artwork

class user_profile(models.Model):
    image_path = models.ImageField(upload_to='static/images/', blank=True)
    display_name = models.CharField(max_length=100)
    profile_visible = models.BooleanField()
    preferred_lang = models.ForeignKey(language, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    students = models.ManyToManyField('self', blank=True)
    likes = models.ManyToManyField(artwork, blank=True)

class list(models.Model):
    name = models.CharField(max_length=100)
    up_id=models.ForeignKey(user_profile, on_delete=models.CASCADE)
    contents = models.ManyToManyField(artwork, blank=True)

class list_content(models.Model):
	pass

Artww/templates/base.html
<!-- this is a basic sketch of the main page it has none funcionalities, but
it maybe help to start to develop our project -->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<title>Art Worldwide</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type = "text/css"/>
	{% block head %}
	{% endblock %}
</head>

<body>
	<!-- Starts header-->
	<!-- logo area -->
	<div id="logo"><img id="logo-img" src="{% static 'pics/icon2.png' %}" alt="Logo"/> <h1 class="label" id="title">Art Worldwide</h1></div>
	<!-- ends logo area -->
	<!-- user area -->
	<div id="user">
	{% if user.user_profile %}
		<a href="/accounts/profile">
			<img class="icon" src="{% static 'pics/avatar.png' %}" alt="avatar"/>
			<span class="label">{{user.user_profile.display_name}}</span>
		</a>
		<a href="/accounts/logout">
			<span class="label">(Log out)</span>
		</a>
	{% else %}
		<a href="/accounts/login"><span class="label">Log in</span></a>
	{% endif %}
	</div>
	<!-- ends of user area -->
	<!-- ads area -->
	<div id="ad-space"><span>Ads here</span></div>
	<!-- ends of ads area -->
	<!--ends header-->
	
	<!-- starts main container -->
	<!--starts sidebar-->
	<div class="sidebar" id="sidebar">
		<!-- start bar of menu -->
		<div id="sidemenu">
			<!--none of the menu button work -->
			<ul>
				<li><a href="{% url 'Index' %}">Home</a></li>
				<li><a href="{% url 'Likes' %}">Liked Art</a></li>
				<li><a class="list-header" href="{% url 'ListAll' %}">Lists</a></li>
			</ul>
		</div>
		<!-- ends bar of menu -->
		<!-- start side list -->
		<!-- we need to start to disgn and create our data base structure so we can start to create
		apps to add funcionalities -->
		<!-- here we can use and app that can get the lists from the data base of a user, but like I said
		we need to figure out the whole data base structure to start to creates models -->
		{% if user.user_profile %}
			<ul class="scrollable" id="lists">
				{% for list in user.user_profile.list_set.all %}
					<li><a href="{% url 'Lists' list.id %}">{{list.name}}</a></li>
				{% endfor %}
			</ul>
		{% endif %}
		<!-- ends side list -->
	</div>
	<!-- ends Sidebar -->

	<!-- starts map container -->
		<!-- I have not figure out how we will make this MAP. I need to do more research -->
		
	{% block main %}
	<div id="map-container">
		{% block content %}
		{% endblock %}
	</div>
	<!-- end of mapcontainer -->

	<!-- starts of top 5 container -->
	<div class="sidebar right" id="top5-container">
		<a class="list-header" href="#">Top 5 Artworks</a>
		<!-- this part is really bad disgned in the future we will need to create and an app
		that collect data fron user then create the top 5 -->
		<ul class="scrollable">
			{% block top5 %}
			<li class="top5">
			<div class="art-description">
			<img class="thumbnail" src="{% static 'pics/icon1.png' %}" alt="Logo">
			<span class="artname">Artwork</span>
			Placeholder text for the description. Placeholder text for the description. Placeholder text for the description...
			</div>
			</li>
			<li class="top5">
			<div class="art-description">
			<img class="thumbnail" src="{% static 'pics/icon1.png' %}" alt="Logo">
			<span class="artname">Artwork</span>
			Placeholder text for the description. Placeholder text for the description. Placeholder text for the description...
			</div>
			</li>
			<li class="top5">
			<div class="art-description">
			<img class="thumbnail" src="{% static 'pics/icon1.png' %}" alt="Logo">
			<span class="artname">Artwork</span>
			Placeholder text for the description. Placeholder text for the description. Placeholder text for the description...
			</div>
			</li>
			<li class="top5">
			<div class="art-description">
			<img class="thumbnail" src="{% static 'pics/icon1.png' %}" alt="Logo">
			<span class="artname">Artwork</span>
			Placeholder text for the description. Placeholder text for the description. Placeholder text for the description...
			</div>
			</li>
			<li class="top5">
			<div class="art-description">
			<img class="thumbnail" src="{% static 'pics/icon1.png' %}" alt="Logo">
			<span class="artname">Artwork</span>
			Placeholder text for the description. Placeholder text for the description. Placeholder text for the description...
			</div>
			</li>
			{% endblock %}
		</ul>
	</div>
	{% endblock %}
	<!-- ends of top 5 container -->
	<!-- ends main container -->

</body>
</html>

Artww/templates/gridview.html
{% load static %}

<div id="main-container">
	<div id="grid-container">
		{% for art in artworks %}
			<a href="{% url 'Artwork' art.id %}">
				<img class="tempartsmall" src="/{{art.image_path}}">
			</a>
		{% endfor %}
	</div>

	<!-- Starts pagination section -->
	<div id="down-menu">
		{% if artworks.has_other_pages %}
			<div class="paginator">
				{% if artworks.has_previous %}
					<a href="?page={{ artworks.previous_page_number }}">
						<div class="iconD">
							<img id="previmg" src="{% static 'pics/prev.png' %}" alt="Previous">
						</div>
					</a>
				{% endif %}
				Page {{ artworks.number }} of {{ artworks.paginator.num_pages }}
				{% if artworks.has_next %}
					<a href="?page={{ artworks.next_page_number }}">
						<div class="iconD">
							<img id="nextimg" src="{% static 'pics/next.png' %}" alt="Next">
						</div>
					</a>
				{% endif %}
			</div>
		{% endif %}
	</div>
</div>